# yaml-language-server: $schema=./quartz/plugins/quartz-plugins.schema.json
configuration:
  pageTitle: '> Analyse With Me'
  pageTitleSuffix: 'miniMinn-Sec'
  enableSPA: true
  enablePopovers: true
  analytics:
    provider: plausible
  locale: en-US
  baseUrl: https://miniminn-sec.pages.dev
  ignorePatterns:
    - private
    - templates
    - .obsidian
  theme:
    fontOrigin: googleFonts
    cdnCaching: false
    typography:
      header: Inter
      body: JetBrains Mono
      code: JetBrains Mono
    colors:
      # lightMode:
      #   light: "#faf8f8"
      #   lightgray: "#e5e5e5"
      #   gray: "#b8b8b8"
      #   darkgray: "#4e4e4e"
      #   dark: "#2b2b2b"
      #   secondary: "#589df6"
      #   tertiary: "#254e85"
      #   highlight: rgba(143, 159, 169, 0.15)
      #   textHighlight: "#fff23688"
      lightMode:
        light: "#0d1117"
        lightgray: "#111820"
        gray: "#646464"
        darkgray: "#9ea1a3"
        dark: "#ebebec"
        secondary: "#4981c9"
        tertiary: "#4981c9"
        highlight: rgba(35, 38, 43, 1.0)
        textHighlight: "#b3aa0288"
      darkMode:
        light: "#0d1117"
        lightgray: "#111820"
        gray: "#646464"
        darkgray: "#9ea1a3"
        dark: "#ebebec"
        secondary: "#4981c9"
        tertiary: "#4981c9"
        highlight: rgba(35, 38, 43, 1.0)
        textHighlight: "#b3aa0288"
plugins:
  - source: github:quartz-community/created-modified-date
    enabled: true
    options:
      defaultDateType: modified
      priority:
        - frontmatter
        - git
        - filesystem
    order: 10
  - source: github:quartz-community/syntax-highlighting
    enabled: true
    options:
      theme:
        light: github-dark
        dark: github-dark
      keepBackground: true 
    order: 20
  - source: github:quartz-community/obsidian-flavored-markdown
    enabled: true
    options:
      comments: true
      highlight: true
      wikilinks: true
      callouts: true
      mermaid: true
      parseTags: true
      parseArrows: true
      parseBlockReferences: true
      enableInHtmlEmbed: true
      enableYouTubeEmbed: true
      enableVideoEmbed: true
      enableCheckbox: true
    order: 30
  - source: github:quartz-community/github-flavored-markdown
    enabled: true
    order: 40
  - source: github:quartz-community/crawl-links
    enabled: true
    options:
      markdownLinkResolution: shortest
    order: 60
  - source: github:quartz-community/description
    enabled: true
    order: 70
  - source: github:quartz-community/latex
    enabled: true
    options:
      renderEngine: katex
    order: 80
  - source: github:quartz-community/citations
    enabled: false
    order: 85
  - source: github:quartz-community/hard-line-breaks
    enabled: true
    order: 90
  - source: github:quartz-community/ox-hugo
    enabled: false
    order: 91
  - source: github:quartz-community/roam
    enabled: false
    order: 92
  - source: github:quartz-community/fonts
    enabled: true
    options:
      fontOrigin: googleFonts
      pageTitle: JetBrains Mono
      page-title: Ubuntu
      body: JetBrains Mono
      header: Inter
      code: JetBrains Mono
  - source: github:quartz-community/remove-draft
    enabled: true
  - source: github:quartz-community/explicit-publish
    enabled: false
  - source: github:quartz-community/unlisted-pages
    enabled: true
    options: {}
    order: 45
  - source: github:quartz-community/encrypted-pages
    enabled: true
    options:
      iterations: 600000
      passwordField: password
      unlistWhenEncrypted: false
      outputPath: static/encryptedContentIndex.json
  - source: github:quartz-community/stacked-pages
    enabled: false
    layout:
      position: afterBody
      priority: 50
      display: all
  - source: github:quartz-community/alias-redirects
    enabled: true
  - source: github:quartz-community/content-index
    enabled: true
    options:
      enableSiteMap: true
      enableRSS: true
  - source: github:quartz-community/favicon
    enabled: true
  - source: github:quartz-community/og-image
    enabled: true
  - source: github:quartz-community/cname
    enabled: true
  - source: github:quartz-community/canvas-page
    enabled: true
  - source: github:quartz-community/content-page
    enabled: true
  - source: github:quartz-community/folder-page
    enabled: true
  - source: github:quartz-community/tag-page
    enabled: true
  - source: github:quartz-community/explorer
    enabled: false
    layout:
      position: left
      priority: 50
  - source: github:quartz-community/graph
    enabled: false
    layout:
      position: right
      priority: 11
  - source: github:quartz-community/search
    enabled: true
    layout:
      position: left
      priority: 18 # Before Table of Contents
      group: toolbar
      groupOptions:
        grow: true
  - source: github:quartz-community/table-of-contents
    enabled: true
    order: 50
    options:
      maxDepth: 2
      minEntries: 0
    layout:
      position: right
      priority: 1000
  - source: github:quartz-community/backlinks
    enabled: false 
    layout:
      position: right
      priority: 50
  - source: github:quartz-community/article-title
    enabled: true
    layout:
      position: beforeBody
      priority: 10
  - source: github:quartz-community/content-meta
    enabled: true
    layout:
      position: beforeBody
      priority: 20
  - source: github:quartz-community/tag-list
    enabled: false
    layout:
      position: beforeBody
      priority: 30
  - source: github:quartz-community/page-title
    enabled: true
    layout:
      position: left
      priority: 10
  - source: github:quartz-community/darkmode
    enabled: false
    layout:
      position: left
      priority: 30
      group: toolbar
  - source: github:quartz-community/reader-mode
    enabled: false
    layout:
      position: left
      priority: 35
      group: toolbar
  - source: github:quartz-community/breadcrumbs
    enabled: false
    layout:
      position: beforeBody
      priority: 5
      condition: not-index
  - source: github:quartz-community/comments
    enabled: true
    options:
      provider: giscus
      options:
        repo: miniMinn24/miniminn-sec
        repoId: R_kgDOS_-MKg
        category: General
        categoryId: DIC_kwDOS_-MKs4C_ipa
        lang: en
    layout:
      position: afterBody
      priority: 10
  - source: github:quartz-community/footer
    enabled: true
    options:
      links:
        GitHub: https://github.com/miniMinn24
        Linkedin: https://www.linkedin.com/in/min-maung-maung-03352028a/
  - source: github:quartz-community/recent-notes
    enabled: true
    options:
      showTags: true
      limit: 6
    layout:
      position: left
      priority: 500
  - source: github:quartz-community/spacer
    enabled: true
    options: {}
    order: 25
    layout:
      position: left
      priority: 25
      display: mobile-only
  - source: github:quartz-community/bases-page
    enabled: true
    options:
      query:
        type: "all"
        filter:
          draft: false
          tags:
            - post
      sort:
        by: created
        order: desc
      view:
        type: cards
    limit: 100
    order: 50
  - source: github:quartz-community/note-properties
    enabled: true
    options:
      includeAll: false
      includedProperties:
        - author
        - category
        - aliases
      excludedProperties: []
      hidePropertiesView: false
      delimiters: ---
      language: yaml
    order: 5
    layout:
      position: beforeBody
      priority: 15
      display: all
  - source:
      name: quartz-themes
      repo: github:saberzero1/quartz-themes
      subdir: plugin
    enabled: false 
    options:
      theme: dark
  - source: github:quartz-community/obsidian-plugin-excalidraw
    enabled: true
    options:
      enableInteraction: true
      darkMode: dark
      exportPadding: 20
    order: 50
layout:
  groups:
    toolbar:
      priority: 35
      direction: row
      gap: 0.5rem
  byPageType:
    "404":
      positions:
        beforeBody: []
        left: []
        right: []
    content: {}
    folder:
      exclude:
        - reader-mode
      positions:
        right: []
    tag:
      exclude:
        - reader-mode
      positions:
        right: []
    canvas: {}
    bases: {}
